apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 6
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx

